name: doctopia_models
description: Doctopia Models Library.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.17.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  freezed_annotation: 
  json_annotation: 
  equatable:


dev_dependencies:
  lints: 
  test: 
  build_runner: 
  freezed: 
  json_serializable: 
