name: doctopia_models
description: Doctopia Models Library.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.17.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable:


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
